### PR TITLE
fix(portal): lib issue

### PR DESCRIPTION
**Pull request by yangpangpangya**
## Description

fix Library Vulnerability scan results as follows

## Related Issue

Library | Vulnerable version | Severity | Fix version | Vulnerability ID
-- | -- | -- | -- | --
@eslint/plugin-kit | 0.2.1 | High 🟡 | 0.2.3 | GHSA-7q7g-4xm8-89cq
cross-spawn | 7.0.3 | High 🟡 | 7.0.5 | GHSA-3xgq-45jj-v275

Library	Vulnerable version	Severity	Fix version	Vulnerability ID
@eslint/plugin-kit	0.2.1	High 🟡	0.2.3	[GHSA-7q7g-4xm8-89cq](https://github.com/advisories/GHSA-7q7g-4xm8-89cq)
cross-spawn	7.0.3	High 🟡	7.0.5	[GHSA-3xgq-45jj-v275](https://github.com/advisories/GHSA-3xgq-45jj-v275)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] CI/CD or documentation update (changes to CI/CD pipeline or documentation)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by DaveXiong** [comment]
@yangpangpangya 
Pls add which Vulnerabilities the patch will fix.

**Comment by yangpangpangya** [comment]
> cross-spawn 7.0.3 High 🟡 7.0.5 [GHSA-3xgq-45jj-v275](https://github.com/advisories/GHSA-3xgq-45jj-v275)

**Comment by yangpangpangya** [comment]
> @yangpangpangya Pls add which Vulnerabilities the patch will fix.

have update in description

**Review by DaveXiong — APPROVED** [review]
LGTM

**Pull request merged**
